# espanso match file

matches:
- trigger: ':n'
  replace: '{{mytime}}'
  vars:
  - name: mytime
    type: date
    params:
        format: '%H:%M'
  - name: mydate
    type: date
    params:
        format: '%Y-%m-%d'
